indent_style = "Block"
use_small_heuristics = true
binop_separator = "Front"
condense_wildcard_suffixes = true
brace_style = "PreferSameLine"
fn_single_line = true
where_single_line = true
format_strings = true
merge_imports = true
match_block_trailing_comma = true
max_width = 180
merge_derives = false
normalize_comments = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
struct_field_align_threshold = 7
tab_spaces = 4
use_try_shorthand = true
wrap_comments = false
blank_lines_upper_bound = 2

